/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 60fd47af892e58a7dd4c4669bcbcdf32)
interface __BaseEnv_CloudflareEnv {
	RATE_LIMITER: RateLimit;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	STRIPE_SECRET_KEY: string;
	NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
	FLAGSHIP_APP_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	RESEND_API_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	OIDC_ISSUER: string;
	OIDC_CLIENT_ID: string;
	OIDC_CLIENT_SECRET: string;
	ADMIN_SESSION_SECRET: string;
	ADMIN_OIDC_GROUPS: string;
	BASE_URL: string;
	CHITCHATS_CLIENT_ID: string;
	CHITCHATS_ACCESS_TOKEN: string;
	CHITCHATS_BASE_URL: string;
	WORKER_SELF_REFERENCE: Fetcher /* emilys-flowers-production */ | Fetcher /* emilys-flowers-preview */ | Fetcher /* emilys-flowers */;
}
declare namespace Cloudflare {
	interface ProductionEnv {
		RATE_LIMITER: RateLimit;
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		STRIPE_SECRET_KEY: string;
		NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
		FLAGSHIP_APP_ID: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		RESEND_API_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		OIDC_ISSUER: string;
		OIDC_CLIENT_ID: string;
		OIDC_CLIENT_SECRET: string;
		ADMIN_SESSION_SECRET: string;
		ADMIN_OIDC_GROUPS: string;
		BASE_URL: string;
		CHITCHATS_CLIENT_ID: string;
		CHITCHATS_ACCESS_TOKEN: string;
		CHITCHATS_BASE_URL: string;
		WORKER_SELF_REFERENCE: Fetcher /* emilys-flowers-production */;
	}
	interface PreviewEnv {
		RATE_LIMITER: RateLimit;
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		STRIPE_SECRET_KEY: string;
		NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
		FLAGSHIP_APP_ID: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		RESEND_API_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		OIDC_ISSUER: string;
		OIDC_CLIENT_ID: string;
		OIDC_CLIENT_SECRET: string;
		ADMIN_SESSION_SECRET: string;
		ADMIN_OIDC_GROUPS: string;
		BASE_URL: string;
		CHITCHATS_CLIENT_ID: string;
		CHITCHATS_ACCESS_TOKEN: string;
		CHITCHATS_BASE_URL: string;
		WORKER_SELF_REFERENCE: Fetcher /* emilys-flowers-preview */;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STRIPE_SECRET_KEY" | "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" | "FLAGSHIP_APP_ID" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID" | "RESEND_API_KEY" | "STRIPE_WEBHOOK_SECRET" | "OIDC_ISSUER" | "OIDC_CLIENT_ID" | "OIDC_CLIENT_SECRET" | "ADMIN_SESSION_SECRET" | "ADMIN_OIDC_GROUPS" | "BASE_URL" | "CHITCHATS_CLIENT_ID" | "CHITCHATS_ACCESS_TOKEN" | "CHITCHATS_BASE_URL">> {}
}
